"""new fields in user model

Revision ID: 5ff9c8c3d301
Revises: e750eee9c283
Create Date: 2018-07-14 00:06:56.118477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff9c8c3d301'
down_revision = 'e750eee9c283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('car_details', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'car_details')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
